AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  env: 
    Description: "enviroment of deploy"
    Type: String
  frontDomain: 
    Description: "domain asigned to bucket frontend"
    Type: String
  hostedZoneId:
    Description: ""
    Default: Z03106681HAK9G20RE56N
    Type: String

Resources:

  PicotaBucketFrontend:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        Fn::Sub: picota-bucket-frontend-${env}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PicotaBucketPolicyFrontend:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: PicotaBucketFrontend
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                Fn::Sub: 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${PicotaCDNOAI}'
            Action: 's3:GetObject'
            Resource: 
              Fn::Sub: ${PicotaBucketFrontend.Arn}/*

  PicotaCDNFrontend:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::Sub: ${frontDomain}
        Origins:
          - DomainName: 
              Fn::GetAtt: [PicotaBucketFrontend, DomainName]
            Id: picota-bucket-frontend
            S3OriginConfig:
              OriginAccessIdentity: 
                Fn::Sub: 'origin-access-identity/cloudfront/${PicotaCDNOAI}'
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: picota-bucket-frontend
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: 
            Ref: PicotaCertificateFrontend
          SslSupportMethod: sni-only

  PicotaCDNOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity'

  PicotaDNSRecords: 
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: 
        Fn::Sub: ${hostedZoneId}
      RecordSets:
        - Name: 
            Fn::Sub: ${frontDomain}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: 
              Fn::GetAtt: PicotaCDNFrontend.DomainName

  PicotaCertificateFrontend:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: 
        Fn::Sub: ${frontDomain}
      DomainValidationOptions:
        - DomainName: dev.picota.org
          HostedZoneId: 
            Fn::Sub: ${hostedZoneId}
      ValidationMethod: DNS

  PicotaRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: 
        Fn::Sub: picota-ecr-${env}