AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  env: 
    Description: "enviroment of deploy"
    Type: String

Resourses:
  PicotaBucketFrontend:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        Fn::Sub: ${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-${env}
